### ISSUE TITLE
bower install ember-spin-box

### ISSUE THREAD

**Issue by jeprussell** [billdami/ember-spin-box#1]
doesn´t work

**Comment by billdami** [comment]
What is the error message you are receiving when you execute that command? Are you able to install other packages via bower without any problems? I just tested it myself from a fresh directory on my machine, and it downloaded with no issues, so the bower configuration seems to be ok.

**Comment by jeprussell** [comment]
![Uploading Screen Shot 2014-06-01 at 11.06.56.png . . .]()

@billdami sorry now working like charm awesome component keep Going
