### ISSUE TITLE
Animation on click

### ISSUE THREAD

**Issue by xypaul** [billdami/ember-spin-box#3]
Really cool library :+1: 

I was just thinking I'd be great if there was an animation if you selected an item via a click. Currently it just jumps straight to the selected value, which feels a little to quick.

Seriously great work though. This is just a suggestion :smile:

**Comment by billdami** [comment]
Thanks for compliments and the input @xypaul. :smile: I actually just released a new version of the component ([v0.0.4](https://github.com/billdami/ember-spin-box/releases/tag/v0.0.4)) a few hours ago, which does in fact add just that; when you click on an unselected visible item, it will animate the transition to that item.

I just updated the [demo page](http://billdami.com/ember-spin-box/) with the new version, so take a look and let me know what you think!

**Comment by xypaul** [comment]
Wow. Really impressed @billdami!!!

Keep up the good work :+1:
